config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pastes#new'
  get 'help' => 'pastes#help'
  resources :pastes, path: 'p'
  post 'paste' => 'pastes#create'
  post 'paste-file' => 'pastes#create_from_file'
  get ':id' => 'pastes#show'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paste.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: pastes
#
#  id                 :integer          not null, primary key
#  body               :text
#  request_info       :text
#  permalink          :text
#  language           :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  auto_destroy       :boolean          default(FALSE), not null
#  will_be_deleted_at :datetime
#
# Indexes
#
#  index_pastes_on_permalink  (permalink) UNIQUE
#

class Paste < ApplicationRecord
  extend Enumerize
  enumerize :language, default: :text, in:
      %i[text markdown pgsql ruleslanguage groovy mathematica ruby yaml livescript xml erlang-repl elm java lua swift
         crystal erb processing javascript stylus brainfuck vbnet go php mercury gherkin cpp arduino applescript delphi
         elixir objectivec lisp scss accesslog xquery pf vbscript clojure vbscript-html haskell livecodeserver properties
         ldif r python powershell dust gradle htmlbars sql actionscript haxe kotlin json ini csp prolog bash makefile excel
         coffeescript fsharp ebnf diff rust cmake routeros scala matlab twig typescript awk haml vim tcl dos perl
         django shell nginx roboconf http css less c cs handlebars smalltalk erlang plaintext dns apache dart tex
         dockerfile d]

  store :request_info, accessors: %i[ip request referer]

  # временно отключили
  # acts_as_paranoid

  before_create :generate_permalink
  before_validation :strip_body

  validates_presence_of :body
  validates_length_of :body, maximum: 512 * 1024

  def to_param
    permalink
  end

  def ttl_days
    ((will_be_deleted_at - Time.now) / (60 * 60 * 24)).round
  end

  def ttl_days=(days)
    self.will_be_deleted_at = days.to_i <= 5000 ? days.to_i.days.from_now : 5000.days.from_now
  end

  private

  def generate_permalink
    permalink = nil
    loop do
      permalink = SecureRandom.hex
      break unless Paste.exists?(permalink: permalink)
    end
    self.permalink = permalink
  end

  def strip_body
    self.body = body.strip if body.present?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Контроллер приложения
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  before_action :set_locale

  rescue_from ActiveRecord::RecordNotFound do
    render file: 'public/404.html', status: :not_found, layout: false
  end

  rescue_from ActionView::MissingTemplate, with: :not_found

  rescue_from I18n::InvalidLocale, with: :locale_error

  private

  def set_locale
    I18n.locale = params[:locale] || session[:locale] || http_accept_language.compatible_language_from(I18n.available_locales)
    session[:locale] = I18n.locale if session[:locale] != I18n.locale
  end

  def locale_error
    render plain: 'Unsupported locale. Available locale is ru/en'
  end
end

app/controllers/pastes_controller.rb
# frozen_string_literal: true

# Контроллер сниппетов
class PastesController < ApplicationController
  before_action :set_paste, only: [:show, :edit, :update, :destroy]

  DEFAULT_TTL_DAYS = 730

  # GET /pastes
  # GET /pastes.json
  def index
    @pastes = Paste.all
    redirect_to root_url
  end

  # GET /pastes/1
  # GET /pastes/1.json
  def show
    @paste.destroy if @paste.auto_destroy? && params[:destroy].present?
  end

  def help
    @html_title = 'Help - xPaste'
  end

  def new
    @paste = Paste.new(ttl_days: DEFAULT_TTL_DAYS)
  end

  # GET /pastes/1/edit
  def edit
    redirect_to paste_url(@paste)
  end

  # curl -d "paste[language]=text" -d "paste[body]=text" localhost:3000/paste
  # curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d ' {"paste":{"language":"text","body":"text", "ttl_days": 365}}'  http://localhost:3000/paste

  # curl -X POST localhost:3000/paste -d ''

  # POST /pastes
  # POST /pastes.json
  def create
    @paste = Paste.new(paste_params)
    @paste.referer = request.env['HTTP_REFERER']
    @paste.request = request.env['REQUEST_URI']
    @paste.ip = request.remote_ip

    @paste.ttl_days = DEFAULT_TTL_DAYS unless paste_params && paste_params[:ttl_days].present?

    respond_to do |format|
      if @paste.save
        format.html do
          if session.present?
            redirect_to paste_url(@paste), notice: 'Paste was successfully created.'
          else
            render body: paste_url(@paste)
          end
        end
        format.text { render :show }
        format.json { render :show, status: :created, location: @paste }
      else
        format.html do
          if session.present?
            render :new
          else
            render body: @paste.errors.full_messages.join('; ')
          end
        end
        format.json { render json: @paste.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_from_file
    language = params[:language]
    request_body = request.body.read.force_encoding('UTF-8')

    body = request_body.strip.encode('UTF-8', invalid: :replace, undef: :replace, replace: '?')

    if body.length > 512 * 1024
      cut_message = "\nText was automatically cut over 512 kb"
      body = body[0, 512 * 1024 - cut_message.length] + cut_message
    end

    @paste = Paste.new(
      language: language,
      body: body,
      auto_destroy: params[:auto_destroy].present?
    )
    @paste.referer = request.env['HTTP_REFERER']
    @paste.request = request.env['REQUEST_URI']
    @paste.ip = request.remote_ip
    @paste.ttl_days = params[:ttl_days] || DEFAULT_TTL_DAYS

    if @paste.save
      render body: paste_url(@paste)
    else
      render body: @paste.errors.full_messages.join('; ')
    end
  end

  # PATCH/PUT /pastes/1
  # PATCH/PUT /pastes/1.json
  def update
    respond_to do |format|
      if @paste.update(paste_params)
        format.html { redirect_to paste_url(@paste), notice: 'Paste was successfully updated.' }
        format.json { render :show, status: :ok, location: @paste }
      else
        format.html { render :edit }
        format.json { render json: @paste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pastes/1
  # DELETE /pastes/1.json
  def destroy
    @paste.destroy
    respond_to do |format|
      format.html { redirect_to pastes_url, notice: 'Paste was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_paste
    @paste = Paste.find_by!(permalink: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def paste_params
    params.require(:paste).permit(:body, :language, :auto_destroy, :ttl_days) if params[:paste].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/pastes_helper.rb
module PastesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @html_title ? @html_title : 'xPaste' %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-89632404-1', 'auto');
        ga('send', 'pageview');
    </script>
  </head>

  <body>
    <div class="ui menu">
      <%= link_to 'xPaste', root_path, class: 'header item' %>
      <%= link_to t('help'), help_path, class: 'item' %>

      <div class="right menu">

        <% if I18n.locale == :en %>
          <%= link_to root_path(locale: 'ru'), class: 'item' do %>
            <i class="ru flag"></i>
          <% end %>
        <% else %>
          <%= link_to root_path(locale: 'en'), class: 'item' do %>
            <i class="gb flag"></i>
          <% end %>
        <% end %>
      </div>

    </div>

    <%= yield %>

  </body>
</html>

app/views/pastes/_copy_to_clipboard.html.erb
<div class="ui input">
  <%= text_field_tag :url, paste_url(@paste), size: 75 %>
</div>

<%= button_tag class: 'ui icon basic button clipboard', data: {clipboard_target: '#url', content: 'Copy to clipboard', variation: 'inverted'} do %>
  <%= semantic_icon 'copy' %>
<% end %>

app/views/pastes/_form.html.erb
<%= form_for(@paste, html: { class: 'ui form' }) do |f| %>
  <% if @paste.errors.any? %>
    <div class="ui negative message">
      <ul>
        <% @paste.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :language %>
    <%= f.select :language, Paste.language.options.sort, {}, { class: 'ui fluid dropdown' } %>
  </div>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, autofocus: true %>
  </div>

  <div class="inline field">
    <%= f.label :ttl_days %>
    <%= f.number_field :ttl_days, max: 5000 %>
    <%= t('activerecord.attributes.paste.days') %>
  </div>

  <div class="field">
    <div class="ui checkbox">
      <%= f.check_box :auto_destroy %>
      <%= f.label :auto_destroy %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit t('.create'), class: 'ui button' %>
  </div>
<% end %>

app/views/pastes/help.html.erb
<div class="ui container">
  <h1><%= t 'help' %></h1>

  <p><%= t('.contact_with_us') %>: ask@southbridge.io /
    <a href="https://southbridge.io" target="_blank">www.southbridge.io</a></p>

  <p><%= t('.open_page') %></p>

  <p><%= t('.create_method.title') %>:</p>
  <ul>
    <li><%= t('.create_method.form') %>;</li>
    <li><%= t('.create_method.text_post') %>;</li>
    <li><%= t('.create_method.json_post') %>.</li>
  </ul>

  <%= t('.post_address') %>:
  <code><%= "#{root_url}paste" %></code>
  <p>
    <%= t('.available_params') %>:</p>
  <pre>
  paste:
    language: text|markdown
    body: <%= t('pastes.help.text_length_limit') %> 512 kb
    auto_destroy: true
    ttl_days: 365
</pre>
  <ul>
    <li>
      <strong>body</strong> - <%= t('pastes.help.required') %>
      . <%= t('pastes.help.max_text_limit') %> - 512 kb.
    </li>
    <li>
      <strong>language</strong> <%= t('pastes.help.one_of_x_values') %>
      <code>text</code> <%= t('pastes.help.or') %> <code>markdown</code>.
      <%= t('pastes.help.default_language') %> (<code>text</code>).
    </li>
    <li>
      <strong>auto_destroy</strong> <%= t('pastes.help.auto_destroy') %>
    </li>
    <li>
      <strong>ttl_days</strong> <%= t('pastes.help.ttl_days') %>
    </li>
  </ul>

  <h2><%= t('pastes.help.text_examples') %></h2>

  <p><%= t('pastes.help.short_text') %>:</p>
  <pre>curl -d "paste[language]=text" -d "paste[body]=short text message" <%= "#{root_url}paste" %></pre>
  <pre>curl -d "paste[language]=text" -d "paste[body]=short text message" -d "paste[ttl_days]=17" <%= "#{root_url}paste" %></pre>
  <pre>curl -d "paste[language]=markdown" -d "paste[body]=**Markdown** _text_ message" <%= "#{root_url}paste" %></pre>
  <pre>curl -d "paste[auto_destroy]=true" -d "paste[language]=markdown" -d "paste[body]=**Markdown** _text_ message" <%= "#{root_url}paste" %></pre>
  <h3><%= t('pastes.help.file_sending') %></h3>
  <p><%= t('pastes.help.long_text') %>:</p>

  <pre>curl -H "Content-Type: text/plain" --data-binary "@file_name" <%= paste_file_url(language: 'markdown') %></pre>

  <p><strong><%= t('pastes.help.long_text_cut') %></strong></p>

  <p><%= t('pastes.help.ttl_days_example') %>:</p>

  <pre>curl -H "Content-Type: text/plain" --data-binary "@file_name" <%= paste_file_url(language: 'markdown', ttl_days: 7) %></pre>

  <p><%= t('pastes.help.auto_destroy_example') %>:</p>

  <pre>curl -H "Content-Type: text/plain" --data-binary "@file_name" <%= paste_file_url(language: 'markdown', auto_destroy: true) %></pre>

  <h2><%= t('pastes.help.json_request') %></h2>
  <pre>
  curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST \
    -d '{"paste":{"language":"text","body":"text"}}'  <%= "#{root_url}paste" %>
</pre>
  <br><br><br>
</div>

app/views/pastes/new.html.erb
<div class="ui container">
  <h1><%= t('pastes.new.title') %></h1>

  <%= render 'form' %>

</div>

app/views/pastes/show.html.erb
<% if @paste.auto_destroy? and params[:destroy].nil? %>
  <div class="ui container">
    <div class="ui center aligned">
      <%= render 'copy_to_clipboard' %>
    </div>

    <br>
    <div class="ui negative message center aligned">
      <div class="header">
        <%= t('pastes.show.destroy_alert') %>
      </div>
      <br>

      <p>
        <%= link_to t('.open_and_destroy'), paste_path(@paste, destroy: true), class: 'ui red button' %>
        <%= link_to t('.go_to_root'), root_path %>
      </p></div>
  </div>
<% else %>
  <div class="ui container">
    <strong><%= Paste.human_attribute_name :language %>:</strong>
    <%= @paste.language.text %>
    <br>
    <strong><%= Paste.human_attribute_name :created_at %>:</strong>
    <%= @paste.created_at %>
    <br>
    <strong><%= Paste.human_attribute_name :will_be_deleted_at %>:</strong>
    <%= @paste.will_be_deleted_at %>
    <br><br>

    <% if @paste.auto_destroy? %>
      <div class="ui negative message center aligned">
        <div class="header">
          <%= t('.paste_destroyed') %>
        </div>
      </div>
    <% else %>
      <%= render 'copy_to_clipboard' %>
    <% end %>
  </div>
  <div class="ui segment" style="margin: 15px">
    <% if @paste.language == 'text' %>
      <pre><%= @paste.body %></pre>
    <% elsif @paste.language == 'markdown' %>
      <%= markdown @paste.body %>
    <% else %>
      <pre id="code"<%= ' class=no-highlight' if params[:highlight] == 'false' %>><code class="<%= @paste.language %>"><%= @paste.body %></code></pre>
    <% end %>
  </div>
<% end %>

app/views/pastes/show.text.erb
<%= paste_url(@paste) %>